[package]
name = "mpc-relay-client"
version = "0.1.0"
edition = "2021"

[dependencies]
mpc-relay-protocol = { path = "../protocol" }
thiserror = "1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"
futures = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "net"] }
tokio-tungstenite = "0.18"
async-stream = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", features = ["sync", "macros"] }
getrandom = {version = "0.2", features = ["js"]}

[dev-dependencies]
anyhow = "1"

[build-dependencies]
rustc_version = "0.4.0"
