[package]
name = "mpc-relay"
version = "0.1.0"
edition = "2021"
description = "Noise protocol websocket relay for MPC/TSS applications"
keywords = ["mpc", "tss", "relay", "crypto", "e2ee"]
license = "MIT OR Apache-2.0"

[workspace]
members = [
  "client",
  "protocol",
  "server"
]

[dependencies]
mpc-relay-protocol = { path = "protocol" }
mpc-relay-server = { path = "server" }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive", "wrap_help", "env"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "fs", "io-util" ] }
axum-server = { version = "0.5", features = ["tls-rustls"] }

[dev-dependencies]
mpc-relay-client= { path = "client" }
serial_test = "2"
futures = "0.3"
hex = "0.4"
binary-stream = { version = "8", features = ["async"] }
serde = {version = "1", features = ["derive"]}
serde_json = "1"
snow = "0.9.2"
