[package]
name = "mpc-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
snow = "0.9.2"
binary-stream = "8"
serde = {version = "1", features = ["derive"]}
serde_json = "1"

[dev-dependencies]
anyhow = "1"
