[package]
name = "mpc-dev-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
axum = { version = "0.6", features = ["headers"] }
axum-macros = "0.3"
axum-server = { version = "0.5" }
axum-extra = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.4", features = ["fs", "trace"] }

[[bin]]
name = "dev-server"
path = "src/dev-server.rs"
